AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  lambdafunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 15
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      EphemeralStorage:
        Size: 512
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
      Layers:
        - arn:aws:lambda:us-east-2:336392948345:layer:AWSSDKPandas-Python311:2
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      SnapStart:
        ApplyOn: None
      PackageType: Zip
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:ListBucket
              - s3:DeleteBucket
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:GetObjectVersion
              - s3:GetBucketPolicy
              - s3:PutBucketPolicy
              - s3:GetBucketAcl
              - s3:PutBucketVersioning
              - s3:GetBucketVersioning
              - s3:PutLifecycleConfiguration
              - s3:GetLifecycleConfiguration
              - s3:DeleteBucketPolicy
            Resource: arn:aws:s3:::dms-*
          - Effect: Allow
            Action:
              - glue:*
              - s3:GetBucketLocation
              - s3:ListBucket
              - s3:ListAllMyBuckets
              - s3:GetBucketAcl
              - ec2:DescribeVpcEndpoints
              - ec2:DescribeRouteTables
              - ec2:CreateNetworkInterface
              - ec2:DeleteNetworkInterface
              - ec2:DescribeNetworkInterfaces
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSubnets
              - ec2:DescribeVpcAttribute
              - iam:ListRolePolicies
              - iam:GetRole
              - iam:GetRolePolicy
              - cloudwatch:PutMetricData
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - s3:CreateBucket
            Resource:
              - arn:aws:s3:::aws-glue-*
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - arn:aws:s3:::aws-glue-*/*
              - arn:aws:s3:::*/*aws-glue-*/*
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - arn:aws:s3:::crawler-public*
              - arn:aws:s3:::aws-glue-*
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - arn:aws:logs:*:*:*:/aws-glue/*
          - Effect: Allow
            Action:
              - ec2:CreateTags
              - ec2:DeleteTags
            Condition:
              ForAllValues:StringEquals:
                aws:TagKeys:
                  - aws-glue-service-resource
            Resource:
              - arn:aws:ec2:*:*:network-interface/*
              - arn:aws:ec2:*:*:security-group/*
              - arn:aws:ec2:*:*:instance/*
          - Sid: BaseAppPermissions
            Effect: Allow
            Action:
              - glue:*
              - redshift:DescribeClusters
              - redshift:DescribeClusterSubnetGroups
              - iam:ListRoles
              - iam:ListUsers
              - iam:ListGroups
              - iam:ListRolePolicies
              - iam:GetRole
              - iam:GetRolePolicy
              - iam:ListAttachedRolePolicies
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSubnets
              - ec2:DescribeVpcs
              - ec2:DescribeVpcEndpoints
              - ec2:DescribeRouteTables
              - ec2:DescribeVpcAttribute
              - ec2:DescribeKeyPairs
              - ec2:DescribeInstances
              - ec2:DescribeImages
              - rds:DescribeDBInstances
              - rds:DescribeDBClusters
              - rds:DescribeDBSubnetGroups
              - s3:ListAllMyBuckets
              - s3:ListBucket
              - s3:GetBucketAcl
              - s3:GetBucketLocation
              - cloudformation:ListStacks
              - cloudformation:DescribeStacks
              - cloudformation:GetTemplateSummary
              - dynamodb:ListTables
              - kms:ListAliases
              - kms:DescribeKey
              - cloudwatch:GetMetricData
              - cloudwatch:ListDashboards
              - databrew:ListRecipes
              - databrew:ListRecipeVersions
              - databrew:DescribeRecipe
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - arn:aws:s3:::aws-glue-*/*
              - arn:aws:s3:::*/*aws-glue-*/*
              - arn:aws:s3:::aws-glue-*
          - Effect: Allow
            Action:
              - tag:GetResources
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - s3:CreateBucket
            Resource:
              - arn:aws:s3:::aws-glue-*
          - Effect: Allow
            Action:
              - logs:GetLogEvents
            Resource:
              - arn:aws:logs:*:*:/aws-glue/*
          - Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
            Resource: arn:aws:cloudformation:*:*:stack/aws-glue*/*
          - Effect: Allow
            Action:
              - ec2:RunInstances
            Resource:
              - arn:aws:ec2:*:*:instance/*
              - arn:aws:ec2:*:*:key-pair/*
              - arn:aws:ec2:*:*:image/*
              - arn:aws:ec2:*:*:security-group/*
              - arn:aws:ec2:*:*:network-interface/*
              - arn:aws:ec2:*:*:subnet/*
              - arn:aws:ec2:*:*:volume/*
          - Effect: Allow
            Action:
              - ec2:TerminateInstances
              - ec2:CreateTags
              - ec2:DeleteTags
            Resource:
              - arn:aws:ec2:*:*:instance/*
            Condition:
              StringLike:
                ec2:ResourceTag/aws:cloudformation:stack-id: arn:aws:cloudformation:*:*:stack/aws-glue-*/*
              StringEquals:
                ec2:ResourceTag/aws:cloudformation:logical-id: ZeppelinInstance
          - Action:
              - iam:PassRole
            Effect: Allow
            Resource: arn:aws:iam::*:role/AWSGlueServiceRole*
            Condition:
              StringLike:
                iam:PassedToService:
                  - glue.amazonaws.com
          - Action:
              - iam:PassRole
            Effect: Allow
            Resource: arn:aws:iam::*:role/AWSGlueServiceNotebookRole*
            Condition:
              StringLike:
                iam:PassedToService:
                  - ec2.amazonaws.com
          - Action:
              - iam:PassRole
            Effect: Allow
            Resource:
              - arn:aws:iam::*:role/service-role/AWSGlueServiceRole*
            Condition:
              StringLike:
                iam:PassedToService:
                  - glue.amazonaws.com
          - Effect: Allow
            Action:
              - s3:*
              - s3-object-lambda:*
            Resource: '*'
          - Effect: Allow
            Action:
              - s3-outposts:Get*
              - s3-outposts:List*
            Resource: '*'
          - Effect: Allow
            Action:
              - datasync:ListTasks
              - datasync:ListLocations
              - datasync:DescribeTask
              - datasync:DescribeLocation*
            Resource: '*'
          - Effect: Allow
            Action:
              - ec2:DescribeVpcs
              - ec2:DescribeSubnets
              - ec2:DescribeSecurityGroups
              - ec2:DescribeNetworkInterfaces
            Resource: '*'
          - Effect: Allow
            Action:
              - outposts:ListOutposts
              - outposts:GetOutpost
            Resource: '*'
          - Effect: Allow
            Action:
              - databrew:CreateDataset
              - databrew:DescribeDataset
              - databrew:ListDatasets
              - databrew:UpdateDataset
              - databrew:DeleteDataset
              - databrew:CreateProject
              - databrew:DescribeProject
              - databrew:ListProjects
              - databrew:StartProjectSession
              - databrew:SendProjectSessionAction
              - databrew:UpdateProject
              - databrew:DeleteProject
              - databrew:CreateRecipe
              - databrew:DescribeRecipe
              - databrew:ListRecipes
              - databrew:ListRecipeVersions
              - databrew:PublishRecipe
              - databrew:UpdateRecipe
              - databrew:BatchDeleteRecipeVersion
              - databrew:DeleteRecipeVersion
              - databrew:CreateRecipeJob
              - databrew:CreateProfileJob
              - databrew:DescribeJob
              - databrew:DescribeJobRun
              - databrew:ListJobRuns
              - databrew:ListJobs
              - databrew:StartJobRun
              - databrew:StopJobRun
              - databrew:UpdateProfileJob
              - databrew:UpdateRecipeJob
              - databrew:DeleteJob
              - databrew:CreateSchedule
              - databrew:DescribeSchedule
              - databrew:ListSchedules
              - databrew:UpdateSchedule
              - databrew:DeleteSchedule
              - databrew:CreateRuleset
              - databrew:DeleteRuleset
              - databrew:DescribeRuleset
              - databrew:ListRulesets
              - databrew:UpdateRuleset
              - databrew:ListTagsForResource
              - databrew:TagResource
              - databrew:UntagResource
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - appflow:DescribeFlow
              - appflow:DescribeFlowExecutionRecords
              - appflow:ListFlows
              - glue:GetConnection
              - glue:GetConnections
              - glue:GetDatabases
              - glue:GetPartitions
              - glue:GetTable
              - glue:GetTables
              - glue:GetDataCatalogEncryptionSettings
              - dataexchange:ListDataSets
              - dataexchange:ListDataSetRevisions
              - dataexchange:ListRevisionAssets
              - dataexchange:CreateJob
              - dataexchange:StartJob
              - dataexchange:GetJob
              - ec2:DescribeSecurityGroups
              - ec2:DescribeVpcs
              - ec2:DescribeSubnets
              - kms:DescribeKey
              - kms:ListKeys
              - kms:ListAliases
              - redshift:DescribeClusters
              - redshift:DescribeClusterSubnetGroups
              - redshift-data:DescribeStatement
              - redshift-data:ListDatabases
              - redshift-data:ListSchemas
              - redshift-data:ListTables
              - s3:ListAllMyBuckets
              - s3:GetBucketCORS
              - s3:GetBucketLocation
              - s3:GetEncryptionConfiguration
              - s3:GetLifecycleConfiguration
              - secretsmanager:ListSecrets
              - secretsmanager:DescribeSecret
              - sts:GetCallerIdentity
              - cloudtrail:LookupEvents
              - iam:ListRoles
              - iam:GetRole
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - glue:CreateConnection
            Resource:
              - arn:aws:glue:*:*:catalog
              - arn:aws:glue:*:*:connection/AwsGlueDataBrew-*
          - Effect: Allow
            Action:
              - glue:GetDatabases
            Resource:
              - arn:aws:glue:*:*:catalog
              - arn:aws:glue:*:*:database/*
          - Effect: Allow
            Action:
              - glue:CreateTable
            Resource:
              - arn:aws:glue:*:*:catalog
              - arn:aws:glue:*:*:database/*
              - arn:aws:glue:*:*:table/*/awsgluedatabrew*
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
            Resource:
              - arn:aws:s3:::databrew-public-datasets-*
          - Effect: Allow
            Action:
              - kms:GenerateDataKey
            Resource:
              - '*'
            Condition:
              StringLike:
                kms:ViaService: s3.*.amazonaws.com
          - Effect: Allow
            Action:
              - secretsmanager:CreateSecret
            Resource: arn:aws:secretsmanager:*:*:secret:AwsGlueDataBrew-*
          - Effect: Allow
            Action:
              - kms:GenerateRandom
            Resource: '*'
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:*:*:secret:databrew!default-*
            Condition:
              ForAnyValue:StringEquals:
                aws:CalledVia:
                  - databrew.amazonaws.com
          - Effect: Allow
            Action:
              - secretsmanager:CreateSecret
            Resource: arn:aws:secretsmanager:*:*:secret:databrew!default-*
            Condition:
              StringLike:
                secretsmanager:Name: databrew!default
              ForAnyValue:StringEquals:
                aws:CalledVia:
                  - databrew.amazonaws.com
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: arn:aws:iam::*:role/*
            Condition:
              StringEquals:
                iam:PassedToService:
                  - databrew.amazonaws.com
          - Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:ListBucketVersions
              - s3:ListBucket
              - s3:GetBucketVersioning
              - s3:GetBucketLocation
              - s3:PutBucketVersioning
              - s3:PutBucketOwnershipControls
              - s3:GetBucketOwnershipControls
            Resource:
              - arn:aws:s3:::*
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:DeleteObject
              - s3:PutObjectVersionAcl
              - s3:GetObjectVersionAcl
              - s3:GetObjectTagging
              - s3:PutObjectTagging
              - s3:GetObjectAcl
              - s3:PutObjectAcl
              - s3:ListMultipartUploadParts
              - s3:PutObject
            Resource:
              - arn:aws:s3:::*/*
          - Effect: Allow
            Action:
              - kms:DescribeKey
              - kms:GenerateDataKey
              - kms:Decrypt
            Resource: '*'
            Condition:
              StringLike:
                kms:ViaService: s3.*.amazonaws.com
          - Effect: Allow
            Action:
              - cloudwatch:GetMetricData
            Resource: '*'
          - Effect: Allow
            Action:
              - events:DeleteRule
              - events:PutTargets
              - events:DescribeRule
              - events:EnableRule
              - events:PutRule
              - events:RemoveTargets
              - events:ListTargetsByRule
              - events:DisableRule
            Resource:
              - arn:aws:events:*:*:rule/AwsBackupManagedRule*
          - Effect: Allow
            Action:
              - events:ListRules
            Resource: '*'
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:DescribeKey
            Resource: '*'
            Condition:
              StringLike:
                kms:ViaService: s3.*.amazonaws.com
          - Effect: Allow
            Action:
              - s3:GetBucketTagging
              - s3:GetInventoryConfiguration
              - s3:ListBucketVersions
              - s3:ListBucket
              - s3:GetBucketVersioning
              - s3:GetBucketLocation
              - s3:GetBucketAcl
              - s3:PutInventoryConfiguration
              - s3:GetBucketNotification
              - s3:PutBucketNotification
            Resource: arn:aws:s3:::*
          - Effect: Allow
            Action:
              - s3:GetObjectAcl
              - s3:GetObject
              - s3:GetObjectVersionTagging
              - s3:GetObjectVersionAcl
              - s3:GetObjectTagging
              - s3:GetObjectVersion
            Resource: arn:aws:s3:::*/*
          - Effect: Allow
            Action:
              - s3:ListAllMyBuckets
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - s3-object-lambda:WriteGetObjectResponse
            Resource: '*'
          - Effect: Allow
            Action:
              - s3-outposts:*
            Resource: '*'
          - Effect: Allow
            Action:
              - datasync:ListTasks
              - datasync:ListLocations
              - datasync:DescribeTask
              - datasync:DescribeLocation*
            Resource: '*'
          - Effect: Allow
            Action:
              - ec2:DescribeVpcs
              - ec2:DescribeSubnets
              - ec2:DescribeSecurityGroups
              - ec2:DescribeNetworkInterfaces
            Resource: '*'
          - Effect: Allow
            Action:
              - outposts:ListOutposts
              - outposts:GetOutpost
            Resource: '*'
